### ISSUE TITLE
Suggestion to Incorporate `eslint-plugin-rxjs-angular` Rules into `eslint-plugin-rxjs-x`

### ISSUE THREAD

**Issue by Dmytro27Ind** [JasonWeinzierl/eslint-plugin-rxjs-x#24]
Hi maintainer,

I hope you’re doing well! I wanted to propose the integration of rules from the `eslint-plugin-rxjs-angular` repository into `eslint-plugin-rxjs-x`. Currently, `eslint-plugin-rxjs-angular` provides only 3 rules, and it would be beneficial to have them included in `eslint-plugin-rxjs-x` to streamline and enhance rule coverage under one cohesive plugin.

In the original `eslint-plugin-rxjs-angular` repository, these rules are marked as optional, which suggests there wouldn't be any conflicts incorporating them as optional rules here as well. This would maintain user flexibility and ensure a smooth, non-disruptive addition to existing configurations.

What are your thoughts on integrating these rules into `eslint-plugin-rxjs-x`? This could help centralize RxJS-related linting rules and simplify plugin management for developers.

Looking forward to your feedback!
Best regards,
Dmytro

**Comment by JasonWeinzierl** [comment]
There's a relevant discussion that has been started here: https://github.com/angular-eslint/angular-eslint/discussions/2094

My personal feelings is the Angular rules should still stay separate because (1) non-Angular projects use RxJS, and (2) the Angular lint rules may someday want to declare an optional peer dependency on Angular. 
- For example, the `takeUntilDestroyed` operator exported by `@angular/core/rxjs-interop` was introduced in Angular 16, and there's likely an opportunity to introduce some lint rules around that operator; but then a peer dependency on Angular 16+ would be out-of-place in the main RxJS lint rules.

Unless the linked discussion bears fruit and something else happens to the Angular rules, my plan is to fork the Angular rules into a new package just like this repository.  Then, I would advertise those Angular rules in this package's README under an Angular heading.

**Comment by JasonWeinzierl** [comment]
For anyone coming back to this thread, I've since forked the Angular rules too.  npm: https://www.npmjs.com/package/eslint-plugin-rxjs-angular-x
